spring:
  application:
    name: student-management-system
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./data/studentdb
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update



